#!/bin/sh

# train/test files are generated by the following function:
# t = 1.0 / (1.0 + exp(-x - 2y + z))

mkdir -p ../data
python build_data.py > ../data/train.txt
python build_data.py > ../data/test.txt

echo -------------------
echo start training
echo -------------------
cmd="../src/cpp/gbdt_train -feature_size 3 \
                           -train_file ../data/train.txt \
                           -max_depth 4 \
                           -iterations 100 \
                           -shrinkage 0.1 \
                           -feature_ratio 1.0 \
                           -data_ratio 1.0 \
                           -debug 0 \
                           -min_leaf_size 0 \
                           -loss SquaredError \
                           -num_of_threads 16"
time $cmd

echo -------------------
echo start predicting
echo -------------------
cmd="../src/cpp/gbdt_predict -model ../data/train.txt.model \
                             -feature_size 3 \
                             -input ../data/test.txt \
                             -debug 1 \
                             -loss SquaredError"
time $cmd

echo -------------------
echo sklearn test
echo -------------------
cmd="python ./sklearn_gbrt_test.py \
     --feature_size 3 \
     --train_file ../data/train.txt \
     --test_file ../data/test.txt \
     --max_depth 4 \
     --iterations 100 \
     --shrinkage 0.1 \
     --loss ls"

time $cmd
