#!/bin/sh

# train/test files are generated by the following function:
# t = 1.0 / (1.0 + exp(-x - 2y + z))

mkdir -p ../../data
python ../../build_data.py > ../../data/train.txt
python ../../build_data.py > ../../data/test.txt

echo -------------------
echo start training
echo -------------------
./gbdt_train ../../data/train.txt
echo -------------------
echo start predicting
echo -------------------
./gbdt_predict ../../data/train.txt.model 3 ../../data/test.txt
